Import('env')
 
env['CCFLAGS'] += ' -O0'
env['CPPPATH'] = [ '../components/avltree/include' ]
env['LIBPATH'] = [ '../components/avltree/lib' ]
env['LIBS'] = [ 'fsdyn' ]

env.Program('avltest.c',
            CPPPATH=[ '#include' ], LIBS=[ 'fsdyn', 'm' ])
env.Program('base64_test.c')
env.Program('bytearray_test.c')
env.Program('charstr_normalization_test.c')
env.Program('charstr_test.c')
env.Program('date_test.c')
env.Program('intset_test.c')
env.Program('priorq_perf.c')
env.Program('priorq_test.c')
